insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (1, 'Notti bianche, Le (White Nights)', 'Frasquito', 'Saltsberger', 70, '320049539-1', 'Russia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (2, 'Derek', 'Andy', 'Arsnell', 72, '615872706-7', 'Indonesia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (3, 'Boiling Point', 'Latisha', 'Neil', 87, '903378645-1', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (4, 'Call Northside 777', 'Billy', 'De Maria', 71, '501527231-6', 'Bosnia and Herzegovina', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (5, 'Wave, The (Welle, Die)', 'Chlo', 'Giraudeau', 11, '788571550-7', 'Tanzania', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (6, 'Maverick', 'Jonis', 'Boughtwood', 39, '886746854-5', 'Colombia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (7, 'Digging Up the Marrow', 'Faye', 'Bottrill', 34, '221376955-9', 'Portugal', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (8, 'Sharpe''s Eagle', 'Cristina', 'Munns', 69, '650162549-1', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (9, 'Horse Boy, The', 'Bax', 'Leele', 12, '168366211-3', 'Ukraine', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (10, 'Sincerely Yours', 'Pren', 'Belchambers', 34, '087194145-7', 'Poland', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (11, 'The Losers', 'Alisun', 'Joanaud', 74, '079601804-9', 'Brazil', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (12, 'That''s What I Am', 'Carmelle', 'Nowaczyk', 30, '108805853-1', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (13, 'Mortal Kombat', 'Cariotta', 'Shoorbrooke', 100, '666566695-6', 'Russia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (14, 'Elegy', 'Bridie', 'Batrop', 42, '910599608-2', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (15, 'Wuthering Heights', 'Rancell', 'Waber', 51, '103245892-5', 'Peru', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (16, 'Call Me Kuchu', 'Milzie', 'Beevis', 94, '529978764-2', 'Mexico', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (17, 'Doomsday Book', 'Bevon', 'Alyoshin', 23, '841680133-9', 'Myanmar', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (18, 'World Unseen, The', 'Kristien', 'Ricket', 47, '978334818-3', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (19, 'House of Dark Shadows', 'Marillin', 'Pidgin', 60, '616200193-8', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (20, 'Killers from Space', 'Garold', 'Kolin', 85, '617886309-8', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (21, 'Deluge, The (Potop)', 'Abbot', 'Squibbes', 4, '754856091-5', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (22, 'Criminal Law', 'Josh', 'De Domenici', 71, '988925251-1', 'Sweden', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (23, 'Hulk', 'Kristyn', 'Spurman', 100, '724991849-4', 'France', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (24, 'Lianna', 'Tanny', 'Stilwell', 26, '465932684-5', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (25, 'Scarecrows', 'Johanna', 'Ginity', 11, '015948709-9', 'Ukraine', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (26, 'Loners (Samotári)', 'Radcliffe', 'Gobolos', 63, '592417853-6', 'Japan', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (27, 'Day, The', 'Cleopatra', 'Gouda', 9, '688750276-3', 'Sweden', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (28, 'Bunny and the Bull', 'Abbye', 'Maides', 85, '397673064-5', 'France', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (29, 'Waterboys', 'Beale', 'Greguoli', 85, '010630356-2', 'Venezuela', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (30, 'Pact, The', 'Andrey', 'Macari', 27, '746595356-1', 'Indonesia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (31, 'Thief of Paris, The (Le voleur)', 'Reyna', 'Cosely', 74, '391137573-5', 'United States', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (32, 'For the Moment', 'Glenden', 'Otton', 28, '275187792-3', 'Russia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (33, 'The Police Serve the Citizens?', 'Diandra', 'Medford', 87, '632801122-9', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (34, 'Wadd: The Life & Times of John C. Holmes', 'Steve', 'Sprigin', 4, '494452841-8', 'France', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (35, 'House', 'Baldwin', 'Goffe', 44, '604964036-X', 'Indonesia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (36, 'Jack Frost', 'Wit', 'Ickov', 27, '020789438-8', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (37, 'Silence, The (Sokout)', 'Dode', 'Youthed', 33, '796677762-6', 'South Korea', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (38, 'Bourne Identity, The', 'Marylee', 'Andor', 88, '869691296-9', 'Philippines', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (39, 'Atlantis: The Lost Empire', 'Judas', 'Heineking', 13, '663466420-X', 'Indonesia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (40, 'Substance of Fire, The', 'Marieann', 'Rowen', 63, '637183849-0', 'Pakistan', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (41, 'Hearts and Minds', 'Inge', 'Orable', 8, '784645612-1', 'Ukraine', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (42, 'Elite Squad (Tropa de Elite)', 'Cris', 'Tollet', 55, '430076180-9', 'Indonesia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (43, 'Horse Soldiers, The', 'Alia', 'Parradice', 2, '931103281-6', 'Russia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (44, 'Four Weddings and a Funeral', 'Patrizia', 'Nunn', 62, '547572959-X', 'Palestinian Territory', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (45, 'Wilde', 'Cob', 'Tour', 80, '199233722-5', 'Peru', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (46, 'Death of Mr. Lazarescu, The (Moartea domnului Lazarescu)', 'Tasha', 'Tamburi', 8, '134322875-1', 'Argentina', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (47, 'Live-In Maid (Cama adentro)', 'Delia', 'Kubicki', 53, '012719966-7', 'Chile', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (48, 'Rehearsals for Extinct Anatomies', 'Karie', 'Spilisy', 47, '358326420-7', 'Peru', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (49, 'Pretty Maids All in a Row', 'Sonny', 'De Dei', 89, '225184236-5', 'Honduras', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (50, 'Trio', 'Dulsea', 'Martynikhin', 79, '923526948-2', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (51, 'Thunderbolt (Pik lik feng)', 'Dominic', 'Borzone', 51, '797249052-X', 'Palestinian Territory', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (52, 'Turning Tide (En solitaire)', 'Evey', 'Wordsworth', 56, '072407928-9', 'Colombia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (53, 'Chain Reaction', 'Ody', 'Binton', 23, '645992697-2', 'Ivory Coast', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (54, 'Illtown', 'Monah', 'Cambden', 36, '725588875-5', 'Indonesia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (55, 'Cabiria', 'Janela', 'Philipsson', 62, '527443192-5', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (56, 'Toy Story 2', 'Kristo', 'Lunbech', 53, '342789837-7', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (57, 'Yours, Mine and Ours', 'Mata', 'Vasilmanov', 56, '891393982-7', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (58, 'Ice Castles', 'Cally', 'Featherstonehaugh', 76, '172649101-3', 'Greece', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (59, 'Life Is Beautiful (La Vita è bella)', 'Carmelia', 'Ortas', 74, '932747127-X', 'Indonesia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (60, 'Love God?, The', 'Chic', 'Dotterill', 65, '348766401-1', 'Indonesia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (61, 'Blackbird', 'Glad', 'O'' Neligan', 15, '781320802-1', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (62, 'Librarian: Quest for the Spear, The', 'Oona', 'Drayn', 57, '162436495-0', 'Indonesia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (63, 'Palookaville', 'Aila', 'Labbet', 7, '628889696-9', 'Sweden', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (64, 'Maurice', 'Maighdiln', 'Boutcher', 64, '022482635-2', 'Kazakhstan', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (65, 'Unconscious (Inconscientes)', 'Irvin', 'Dottrell', 1, '119750585-7', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (66, 'Starbuck', 'Wendell', 'Manes', 89, '742018939-0', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (67, 'Flash Gordon', 'Tabitha', 'Eschelle', 66, '906115542-8', 'Philippines', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (68, 'Blame it on Fidel! (La faute à Fidel!)', 'Harlene', 'Helix', 62, '585958581-0', 'Cuba', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (69, 'Four Seasons, The', 'Kristian', 'Tembey', 19, '467808010-4', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (70, 'Once in a Lifetime: The Extraordinary Story of the New York Cosmos', 'Jeffrey', 'Hinckley', 56, '429257937-7', 'Portugal', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (71, '48 Shades', 'Agace', 'Vynall', 60, '413210078-2', 'Armenia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (72, 'Pohjanmaa', 'Karia', 'Keming', 95, '975331487-6', 'Sri Lanka', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (73, 'Stranger in Town, A', 'Earlie', 'Giovanitti', 30, '855655179-3', 'Dominican Republic', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (74, 'The Sea That Thinks', 'Allissa', 'Crosher', 29, '336570740-9', 'Vietnam', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (75, 'Boy and His Dog, A', 'Merola', 'Shelley', 92, '153102150-6', 'Canada', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (76, 'When a Man Loves a Woman', 'Wallis', 'Roseman', 75, '575718044-7', 'Indonesia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (77, 'Tomcats', 'Rockey', 'Tapply', 30, '727461038-4', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (78, 'Beefcake', 'Tamara', 'Titchen', 94, '483550761-4', 'Ukraine', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (79, 'Iron Ladies, The (Satree lek)', 'Steward', 'O''Scollee', 80, '968843738-7', 'United States', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (80, 'Kabluey', 'Kristin', 'Amps', 19, '855533829-8', 'Peru', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (81, 'Vince Vaughn''s Wild West Comedy Show: 30 Days & 30 Nights - Hollywood to the Heartland', 'Winthrop', 'Alexsandrovich', 19, '915101271-5', 'Croatia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (82, 'Call Me Madam', 'Silvano', 'Roobottom', 49, '808226658-9', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (83, 'Kart Racer', 'Felita', 'Fudge', 37, '951746888-1', 'Sweden', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (84, 'Wuthering Heights', 'Cass', 'Armitt', 54, '561358898-8', 'Czech Republic', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (85, 'Clonehunter', 'Norman', 'Buessen', 98, '077009988-2', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (86, 'Bhutto', 'Leta', 'Haysham', 66, '148804314-0', 'Albania', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (87, 'Quand je serai petit', 'Nelle', 'Bowcher', 23, '810914198-6', 'Brazil', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (88, 'Renaissance Man', 'Kimbra', 'Bromehed', 81, '917577964-1', 'Indonesia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (89, 'Maniac', 'Yolane', 'Vick', 74, '761803436-2', 'Philippines', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (90, 'Peanut Butter Solution, The', 'Karlis', 'Dinnage', 51, '143682230-0', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (91, 'Joke, The (Zert)', 'Leoline', 'Vickery', 37, '321999844-5', 'Ukraine', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (92, 'Return of the Living Dead 3', 'Zorine', 'MacWilliam', 30, '582024715-9', 'France', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (93, 'Cold in July', 'Fawn', 'Ferrea', 39, '248928917-9', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (94, 'Sweeney Todd: The Demon Barber of Fleet Street', 'Joana', 'Guiduzzi', 10, '341212343-9', 'Netherlands', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (95, 'Shakedown', 'Sigismundo', 'Ells', 88, '180660067-6', 'Greece', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (96, 'Great Buck Howard, The', 'Libby', 'Wesley', 50, '398080222-1', 'China', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (97, 'My Sex Life... or How I Got Into an Argument (Comment je me suis disputé... (ma vie sexuelle))', 'Tonya', 'Collibear', 99, '532353091-X', 'Madagascar', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (98, 'Lips of Blood (Lèvres de sang)', 'Isidro', 'Troughton', 52, '488999892-6', 'Russia', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (99, 'Borderland', 'Lorie', 'Thomerson', 36, '323390614-5', 'South Africa', 0);
insert into books (id, title, author_name, author_surname, pages, isbn, country, is_booked) values (100, 'Sisters of the Gion (Gion no shimai)', 'Jami', 'Quest', 29, '024617198-7', 'Argentina', 0);
